apply plugin: 'java'
apply plugin: 'maven-publish'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
version = '1.0'
group = 'com.github.Anuken'

sourceSets.main.java.srcDirs = [ "src/" ]
sourceSets.main.java.exclude("emu/**")

repositories {
    mavenCentral()
 	maven { 
 		url "https://oss.sonatype.org/content/repositories/snapshots/"
 	}
}

ext {
	gdxVersion = '1.14.2'
}

task sourcesJar(type: Jar, dependsOn: classes) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

dependencies {
	implementation "com.badlogicgames.gdx:gdx:$gdxVersion"
    implementation "com.badlogicgames.gdx:gdx-controllers:1.9.13"
}
